options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: brainlinks-be
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/brainlinks/be:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir: brainlinks-be
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/brainlinks/be:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'brainlinks-be'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/brainlinks/be:latest'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/brainlinks/be:latest'